**异常处理：对可以出现的问题提前作出处理，从面提高程序的健壮性。**

在C中一般用返回值的方式来判断代码执行是否正确，面在JAVA是以Exception类来统一管理。

JAVA虚拟机方法调用栈与异常处理：
在主纯种中，堆栈的最底部就是程序的入口main()，在main()中调用一个方法就将该方法置入栈顶，位于栈顶的方法就是正在执行的方法。如果在方法执行中抛出了异常，则会先在该方法中搜索处理异常的代码块，如果没有，则会弹出该方法，继续在栈中往下搜索处理异常的代码块。（这会造成在抛出异常后的语句无法执行。）

当搜索异常一直到栈底部仍然没有找到处理异常的catch块时(仍然抛出异常)，就是会执以下步骤：
a. 调用异常类的printStackTrace()方法：
```java
Exception in thread "main" SpecialException:Out of money
	at Sample.methodA(Sample.java:3)
    at Sample.methodB(Sample.java:7)
    at Sample.main(Sample.java:11)
```
b.如果该线程不是主线程，那么终止这个线程；如果是主线程，即在main()方法中，那么整个应用程序终止。

**try...catch:**
```java
try{
	抛出异常
}catch(SQLException){
	异常处理
}catch(IOException){
	异常处理
}finally{	//finally必须在catch{}之后
	必须执行的语句
}
```

一个代码块中可能抛出异常，有两种处理方式：
```java
//1.直接捕获异常，这种不常用，这样用的意义不大
public void methodA(int money){
	try{
    	if(--money<=0)throw new SpecialException("Out of money");
    }catch(SpecialException e){
    	处理异常
    }
}

//2.在方法的声明处通过throws抛出异常
public void methodA(int money) throws SpecialException{
	if (--money<=0) throw new SpecailExcption("Out of money");
}
```
抛出异常时，也可使用try{}并还抛出异常，如：try{}后面可以只跟finally{},这表明在此方法中无法处理异常，继续throws抛出给后面的调用方法来处理，此时try{}...finally{}感觉没什么意义呀,增强可读性？哦有的，有finally哟
```java
public  void test()throws SpecialException{
	try{
    	new Sample().methodA(1);
        System.out.println("test");
    }finally{
    	System.out.println("Finally");
    }
}
```

try不能单独存在，后面必须至少有一个catch或者finally

变量作用域：在各个代码块中是独立的，如在try代码块中定义的变量，在catch和finally中无法访问

**throw** 与 **throws**一个用于一般直接抛出异常，一个用于一个方法后面的声明。
```java
public void run() throws CarWrongException{
	if(xxx1) throw new Exception1();
    if(xxx2) throw new Exception2();
}
```

throw语句抛出的对象必须是java.lang.Throwable类或者子类的实例：
`throw new String("some wrong");	//编译出错`

当try后有多个catch语句时，会从上到下依次搜索处理异常的catch，如果是当前类，或是当前类的父类则处理之。所以不能打异常的子类放在父类的下面：
```java
try{
	code1;
}catch(SQLException e){
	System.out.println("SQLException");
}catch(Exception e){
	System.out.println("Excepiton");
}catch(IOException e){	//编译错误，是Exception的子类，不能放在它之下，它永远执行不了
	System.out.println("IOException");
}
```

throw语句后面不允许紧跟其他语句，因为这些语句永远不会执行：
```java
public void method(int money) throws Exception{
	try{
    	if(--money<=0){
        	throw new SpecialException("Out of money");
            money=1;	//编译错误
        }
    }catch(Exception e){
    	throw e;
        moeny = 0;	//编译错误
    }finallly{
    	System.out.println("Finally");
    }
}
```

**java.lang.System.exit()**方法在异常流程中的反应：
在try{}或者catch{}使用exit()方法，执行会立即停止当前**进程**，不会再执行之后的语句。

**return**语句在异常流程中的反应：
return用于立即退出本方法，而在try或catch代码块中执行return语句时，如果有finally代码块，会先执行finally中的代码。
但，finally代码块虽然在return之前执行，但finally代码不能通过重新赋值来改变return的返回值:
```java
public static int test(){
	int a=0;
    try{
    	return a;
    }finally{
    	a=1;
    }
}
public static void main(String args[])throws Exception{
	System.out.println(test());	//打印0
}
```
以上程序在finally中修改了a的值为1，但返回时为0，它不能改变返回的值。

建议不要在finally中使用return语句，它会导致两种情况。
a.finally中虽不能修改返回变量的值，但可覆盖try和catch代码块中的return语句
b.如果在try或catch代码中有抛出异常，return语句会使抛出的异常丢失，使异常中断后面无法catch到。

####**JAVA异常类：**
在JAVA中所有的异常类的祖先都是java.lang.Throwable类，它的实例表示具体的异常对象，可以用throw抛出。
Throwable类中常用方法：
* getMessage()---返回String类型的异常信息。
* printStackTrace()---打印跟踪方法调用栈面获得的详细异常信息。

Throwable类有两个直接子类：
**Errord类**：表示仅靠程序本身无法恢复的错误，如内存不足，或虚拟机方法调用栈溢出，多数情况下建议程序终止。
**Exception**:表示程序本身可以处理的异常。当程序运行时出现这类异常，应尽可能地处理，使程序恢复运行。

Throwable-->Error-->SomeError...
Throwable-->Exception-->IOException...
Throwable-->Exception-->RuntimeException-->Some...

RuntimeException运行时异常：
编译器不会检查它，也就是说，当程序中出现运行时异常时，即使没有使用try...catch也能通过编译。但在运行时异常发生时，如果没有处理，则会导致程序异常终止。

除了RuntimeException及其子类外，其它的Exception类及其子类都属于受检查异常（CheckedException），这类异常编译器会在编译时检查是否用try...cathc捕获它，或使用throws声明抛出，不然编译不通过。

**运行时异常 与 受检查异常：**
受检查异常是可以处理的异常。
运行时异常表示无法让程序恢复运行的异常，导致这种异常的原因通常是执行了错误操作造成。一量发生了运行时异常，建议终止程序，因为发生这种错误通常是无法挽回的，因此JAVA编译器不检查这种异常。这种错误通常通过编写者自己注意代码的正确，避免发生错误。

**运行时异常 与 错误：**
相同处是编译器都不会检查它们，发生这样的错误时，都会终止进程。
不同处是Error是由虚拟机抛出，在JDK中定义了一些错误，如OutOfMemoryError,StackOutOfMemoryError，在程序中一般不会扩展Error类来创建用户自定义的错误类。而RuntimeException类表示程序代码中的错误，它是可以扩展的，可扩展它来创建相应的类。

**异常转译 与 异常链：**
异常转译：当一个catch捕获一个异常后，重新根据情况重新抛出一个new的异常对象。

异常链：把原始异常包装为新的异常类，也就是说在新的异常类中封装了原始异常类，这有助于查找产生异常的根本原因。（通常在异常类中增加一个 Throwable类型的变量 来实现）

在JAVA中一次中能**抛出一个异常**，如果想一次**抛出多个异常**，可以自行定义一个包含异常集合的类来实现。





























